dist: trusty
# We would really prefer to use `sudo: false` but that breaks kcov.
# see: https://github.com/travis-ci/travis-ci/issues/9061
sudo: required
language: rust
rust:
- 1.23.0
- stable
- beta
- nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - wget

script: ci/script.sh
after_success: ci/after_success.sh

notifications:
  email:
    on_success: never
branches:
  only:
  - master
