[package]
name = "remake"
version = "0.1.0"
authors = ["Ethan Pailes <ethanpailes@gmail.com>"]

[dependencies]
regex = "0.2"
regex-syntax = "0.5"
lalrpop-util = "0.15"

[build-dependencies]
lalrpop = "0.15"
