[package]
name = "remake"
version = "0.1.0"
authors = ["Ethan Pailes <ethanpailes@gmail.com>"]

[dependencies]
regex = "1.0.0"
regex-syntax = "0.6"
lalrpop-util = "0.15"
failure = "0.1.1"

[build-dependencies]
lalrpop = "0.15"
