#!/bin/bash

set -ex

coveralls_id=

while true; do
  case "$1" in
    --coveralls-id)
      coveralls_id="$2"
      shift 2
      ;;
    *)
      break
      ;;
  esac
done

# make sure the test executable really exists
cargo test --verbose --no-run

exe=$(find ./target/debug -executable -wholename "./target/debug/remake-*" | head -n1)

KCOV_ARGS=""
if [ -n "$coveralls_id" ]; then
    KCOV_ARGS="--coveralls-id=$coveralls_id"
fi
kcov ${KCOV_ARGS} \
    --verify \
    --include-pattern '/remake/src/' \
    target/cov \
    ${exe}
